DROP TABLE practiceDB.users_groups;

DROP TABLE practiceDB.users;
DROP TABLE practiceDB.groups;
DROP SCHEMA practiceDB RESTRICT;
CREATE SCHEMA practiceDB;

CREATE TABLE practiceDB.users (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  login VARCHAR(20) UNIQUE NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE practiceDB.groups (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(20) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE practiceDB.users_groups (
  id_user INT NOT NULL,
  id_group INT NOT NULL,
  UNIQUE (id_user, id_group)
);

ALTER TABLE practiceDB.users_groups
ADD CONSTRAINT key_user
FOREIGN KEY (id_user)
REFERENCES practiceDB.users(id)
  ON DELETE CASCADE;
ALTER TABLE practiceDB.users_groups
ADD CONSTRAINT key_group
FOREIGN KEY (id_group)
REFERENCES practiceDB.groups(id)
  ON DELETE CASCADE;

insert into practiceDB.users(id, login) values (default, 'ivanov');
insert into practiceDB.groups(id, name) values (default, 'teamA');